# Generated by Django 3.2.5 on 2021-07-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210711_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='tweet.tweet'),
        ),
    ]
