# Generated by Django 3.2.5 on 2021-10-14 12:10

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_comment_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tweet.models.get_image_directory),
        ),
    ]
