# Generated by Django 3.2.5 on 2022-01-22 07:33

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_auto_20211016_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=tweet.models.get_image_directory),
        ),
    ]
