# Generated by Django 3.2.5 on 2021-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210711_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Profile photo'),
        ),
    ]
