# Generated by Django 3.2.5 on 2022-01-10 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211016_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', related_query_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
