version: '3.7'

services:
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  web:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - db
    command: gunicorn twitter.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
volumes:
  static:
  mysql_data: