version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - db
    command: gunicorn twitter.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
volumes:
  static:
  postgres_data: